export const resources=[
{slug:'different-needs-at-work',category:'Workplace guides',type:'WORKPLACE GUIDE',title:'Making space for different needs at work',description:'Practical ways to help everyone contribute comfortably.',color:'sage',symbol:'↔',sections:[
{title:'Start with the person',text:'Everyone brings different experiences, routines and preferences to work. Invite employees to tell you what would help them contribute comfortably. Keep the conversation private and let them choose how much to share.'},
{title:'Look at everyday routines',text:'Consider how break times, shared spaces, food and team events work for your people. Ask whether any small changes would make participation easier. Explore practical options together, including the needs of the wider team.'},
{title:'Make space without making assumptions',text:'If someone asks for a change to their working environment, find out what would be useful. That may mean access to a quiet shared space, clearer information or a different way to join a team activity. Discuss privacy and how the arrangement can work for others too.'},
{title:'Plan ahead, then check in',text:'Talk about upcoming events, schedules and team commitments early enough to consider different needs. Agree on practical arrangements through your usual workplace processes. Check in afterwards rather than assuming the first solution will always fit.'}],takeaway:'Try asking: “Is there anything about the way we work that would help you feel more comfortable or included?”'},
{slug:'what-to-ask',category:'Conversation guides',type:'CONVERSATION GUIDE',title:'When you’re not sure what to ask',description:'A little curiosity can open up a better conversation.',color:'sand',symbol:'“',sections:[
{title:'Ask permission to be curious',text:'Choose a comfortable moment and a private setting. You might say, “I’d like to understand what would work best for you. Would you be comfortable talking about it?” Let the person set the pace.'},
{title:'Ask about preferences, not a whole community',text:'“What would be helpful for you?” is more useful than asking someone to speak for an entire community. Australian Muslim and diverse Middle Eastern communities include many different experiences and perspectives. Ask about the person’s own preferences.'},
{title:'Listen without rushing to explain',text:'Allow the person to finish. Reflect back what you heard and check your understanding. If something surprises you, stay curious rather than expecting the person to justify it.'},
{title:'Agree on what happens next',text:'Acknowledge what the person has shared. Ask what they would like to happen, explain what you can explore and agree before sharing any details with someone else.'}],takeaway:'Try asking: “Have I understood that correctly? What would a useful next step look like for you?”'},
{slug:'inclusive-events',category:'Checklists',type:'PRACTICAL CHECKLIST',title:'Planning a more inclusive team event',description:'Thoughtful details that help more people feel welcome.',color:'pink',symbol:'＋',sections:[
{title:'Before you choose a date',text:'Give people a chance to flag scheduling needs privately. Consider whether timing could affect attendance or participation, and offer an alternative way to connect when useful.'},
{title:'Make dietary questions routine',text:'Ask everyone about their dietary requirements without singling anyone out. Confirm ingredients and preparation with the caterer, label options clearly and let people choose what is right for them.'},
{title:'Think beyond a single activity',text:'Consider options that allow participation without alcohol, particular food choices or physical contact. Avoid making someone explain why they choose not to join part of an activity.'},
{title:'Share the practical details',text:'Tell people what to expect: the location, timing, food, activities and how to ask a private question. Make the contact person clear.'},
{title:'Learn for next time',text:'Invite feedback on what worked and what could be more welcoming. Use what people share to improve your next event, without assuming their preferences will always be the same.'}],takeaway:'A useful final check: “Can everyone choose how to take part without having to explain or defend that choice?”'}
];
export const faqs=[
['Do I need to know which service I need?','No. Start with what’s on your mind. A question or a little context is enough, and we can explore the most useful next step together.'],
['Who is Crescent Consulting Group for?','Our main focus is Australian employers, HR and workplace teams, schools, educational institutions, and community or cultural staff seeking to engage respectfully with Australian Muslim and diverse Middle Eastern communities. Community members are welcome to explore resources and ask about connections.'],
['Can I request a call rather than write a long message?','Yes. Choose “Request a call” on the conversation page and leave a sentence or two about what you’d like to discuss. You can include preferred times and your time zone. A person needs to confirm a time with you; submitting a request does not book a meeting.'],
['Do you speak for every community?','No. Muslim and Middle Eastern communities include different, sometimes overlapping, identities, cultures and individual perspectives. We help people explore those perspectives and make appropriate connections, without claiming to speak for everyone.'],
['What if a situation needs specialist support?','We’ll discuss the context before proposing a next step. That may mean a further conversation or a referral to someone better placed to help. Any introduction or sharing of details should be agreed with you first.'],
['Is this legal advice or religious guidance?','No. Our focus is cultural understanding and practical conversation. We don’t provide legal representation, religious rulings, compliance certification or a replacement for workplace grievance processes.'],
['What happens after I send a request?','Your request is saved for review. A person will follow up on the request. You can also contact us directly at 0436 279 219.']
];
